/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rossum;

public class MariusTest extends RobotTestBed {
    static {
        System.setProperty("robocode.home", "c:/robocode");
        System.setProperty("WORKINGDIRECTORY", "c:/robocode");
    }
    @Override
    public String getRobotNames() {
        return "rur.Marius,sample.crazy";
    }
}
