/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rossum;

public class MariusTest extends RobotTestBed {
    public MariusTest(){
        isDumpingOutput=true;
    }

    @Override
    public String getRobotNames() {
        return "rossum.Marius,sample.Crazy";
    }
}
