/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rossum;

public class RurWallsTest extends RobotTestBed {
    public RurWallsTest(){
        isDumpingOutput=true;
    }

    @Override
    public String getRobotNames() {
        return "rossum.RurWalls,sample.Crazy";
    }
}
