/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rossum;

import robocode.robotinterfaces.IAdvancedEvents;
import robocode.robotinterfaces.IAdvancedRobot;
import robocode.robotinterfaces.IBasicEvents;
import robocode.robotinterfaces.peer.IAdvancedRobotPeer;
import robocode.robotinterfaces.peer.IBasicRobotPeer;
import rossum.common.Board;
import rossum.common.Receiver;

import java.io.PrintStream;

public class Marius implements IAdvancedRobot, Runnable {
    public Receiver receiver;
    private Board board;

    public Marius() {
        board = new Board();
        receiver = new Receiver(board);
    }

    @Override
    public void run() {
        while (!board.currentTurn.isRoundEnded){
            board.out.println("pre-exec");
            board.peer.execute();
            board.out.println("post-exec");
        }
    }

    @Override
    public IAdvancedEvents getAdvancedEventListener() {
        return receiver;
    }

    @Override
    public Runnable getRobotRunnable() {
        return this;
    }

    @Override
    public IBasicEvents getBasicEventListener() {
        return receiver;
    }

    @Override
    public void setPeer(IBasicRobotPeer peer) {
        this.board.peer = (IAdvancedRobotPeer) peer;
    }

    @Override
    public void setOut(PrintStream printStream) {
        this.board.out = printStream;
    }
}

