/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.8.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
    mavenLocal()
}

dependencies {
    implementation("net.sf.robocode:robocode.api:1.9.4.0")

    testImplementation("junit:junit:4.13")
    testImplementation("net.sf.robocode:robocode.core:1.9.4.0")
    testImplementation("net.sf.robocode:robocode.host:1.9.4.0")
    testImplementation("net.sf.robocode:robocode.battle:1.9.4.0")
    runtimeOnly("net.sf.robocode:robocode.samples:1.9.4.0")
}

tasks {
    register("copySamples", Copy::class) {
        from({
            configurations.runtimeClasspath.get().filter { it.name.endsWith("jar") && it.name.contains("robocode.samples") }.map {
                zipTree(it)
            }
        })
        into("../sandbox/robots")
    }
    test {
        dependsOn("copySamples")
    }
}